--- 
abstract: Automated REST Method Dispatching
author: Adam Jacob <adam@stalecoffee.org>, with lots of help from mst and jrockway
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Action-REST
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7001
  Class::Inspector: 1.13
  Data::Dump: 0
  Data::Serializer: 0.36
  LWP::UserAgent: 2.033
  Module::Pluggable::Object: 0
  Params::Validate: 0.76
  URI::Find: 0
  YAML::Syck: 0.67
  perl: 5.8.1
version: 0.41
