---
abstract: 'Automated REST Method Dispatching'
author:
  - 'Tomas Doran <bobtfish@cpan.org>'
build_requires:
  LWP::UserAgent: '5.00'
  Test::More: '0.88'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Action-REST
requires:
  Catalyst::Runtime: '5.80030'
  Class::Inspector: '1.13'
  JSON::MaybeXS: '0'
  MRO::Compat: '0.10'
  Module::Pluggable::Object: '0'
  Moose: '1.03'
  Params::Validate: '0.76'
  URI::Find: '0'
  namespace::autoclean: '0'
resources:
  Authority: cpan:BOBTFISH
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Catalyst-Action-REST
version: '1.20'
