---
abstract: 'Automated REST Method Dispatching'
author:
  - 'Adam Jacob <adam@stalecoffee.org>, with lots of help from mst and jrockway'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-REST
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80
  Class::Inspector: 1.13
  Data::Serializer: 0.36
  LWP::UserAgent: 2.033
  MRO::Compat: 0.10
  Module::Pluggable::Object: 0
  Moose: 0
  Params::Validate: 0.76
  URI::Find: 0
  YAML::Syck: 0.67
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bobtfish/catalyst-action-rest
version: 0.80
