---
abstract: 'Automated REST Method Dispatching'
author:
  - 'Tomas Doran <bobtfish@cpan.org>'
build_requires:
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-REST
requires:
  Catalyst::Runtime: 5.80030
  Class::Inspector: 1.13
  LWP::UserAgent: 2.033
  MRO::Compat: 0.10
  Module::Pluggable::Object: 0
  Moose: 1.03
  Params::Validate: 0.76
  URI::Find: 0
  namespace::autoclean: 0
resources:
  Authority: cpan:BOBTFISH
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Catalyst-Action-REST
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Action-REST.git
version: 1.14
